--- 
run_list: 
- tvdinner
tvd: 
  class: TVDinner
  name: tvdinner
  author: Tom Bombadil
  email: amanibhavam@destructuring.org
  summary: Generates a tvdinner project
  description: Generrates a tvdinner project
  homepage: http://destructuring.org/tvd-tvdinner
  git_url: https://github.com/destructuring/tvd-tvdinner
